[package]
name = "rig-entertainer-ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
openssl = { version = "0.10.68", features = ["vendored"]}
rig-core = "0.3.0"
tokio = { version = "1.41.0", features = ["full"] }
